version: "3.9"

services:
  # API application
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 4042:4042
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sql
      - POSTGRES_DB=breaking_news
    depends_on:
      - db

  # listener application
  listener:
    build:
      context: .
      dockerfile: listener/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sql
      - POSTGRES_DB=breaking_news
    depends_on:
      - db

  # UI application
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sql
      - POSTGRES_DB=breaking_news
